version: '3.1'

services:
  db:
    image: postgres:12-alpine
    container_name: leetcode_postgres
    #restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres