version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    container_name: leetcode_postgres
    #restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql:8.0.19
    #command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: leetcode
      MYSQL_USER: leetcode
      MYSQL_PASSWORD: leetcode
      MYSQL_DATABASE: leetcode